### ISSUE TITLE
change from element mxd_name to element map_name 

### ISSUE THREAD

**Issue by clairebyrne** [mapaction/mapaction-toolbox#182] opened 2020-08-28 14:52 UTC
## Expected Behavior  
The templates now have a text element with the more generic name of **map_name** instead of **mxd_name**. 
This is to allow for QGIS and Pro scenarios. 
The layout tool should be changed to use map_name element instead of mxd_name. 
The element checker should be updated similarly. 
In the output XML, the Export tool should create an xml tag called mapfilename, instead of mxdfilename

## Actual Behavior
The layout tool currently updates the text element **mxd_name** for the Map Document, and pulls the value from the file name. 
In the output XML, the Export tool creates an xml tag called mxdfilename. 

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

- Toolbar Version: 4.1.7459.3891
- ArcGIS Version and Edition: 10.6.1
- MapAction laptop (yes/no): no
- Windows Version: 10

**Comment by harry-gibson** [comment] 2020-10-02 19:32
The map_name element is not visible on the layout of any template. 
We (@harry-gibson @clairebyrne @dconnaghanx ) therefore see no reason to use it at all. 
The mapfilename tag in the xml will now be populated with the actual filename of the mxd (and this will be shown, readonly, in the export dialog). It will be removed from the Layout tool. 
The xml also contains a ref tag which appears to be (and will continue to be) a duplicate of mapfilename (previously of mxdfilename)

**Comment by harry-gibson** [comment] 2020-10-12 11:17
Issue is fixed, re-open if any complaints ensue due to the new fixed relationship between mxd filename and value in xml

**Closed by harry-gibson** 2020-10-12 11:17 UTC
Labels: Priority-Medium, bug, export-tool, layout-tool
