### ISSUE TITLE
Layout Tool - Time & Date

### ISSUE THREAD

**Issue by macsims1** [mapaction/mapaction-toolbox#112] opened 2015-02-25 14:55 UTC
Add Time and Date fields to layout tool so that they can be updated either in the layout or for the export - this now looks like something Claire has put in, so delete if needed.

**Comment by andrewphilipsmith** [comment] 2016-05-23 16:22
Duplicate of this issue https://github.com/mapaction/mapaction-toolbox/issues/107

**Closed by andrewphilipsmith** 2016-05-23 16:22 UTC
Labels: duplicate
